### ISSUE TITLE
issue in function mergeEDB() for 1N validation

### ISSUE THREAD

**Issue by laouer** [usnistgov/frpc#1]
Hi,
when doing our 1vsN validation tests, we get an issue in the merged manifests file (also in fork 1 )
The problem occurs when, in the same run, some generated templates have different sizes.

we correct the problem from our side using the attached patch

Regards
[run_testdriver.sh.patch.txt](https://github.com/usnistgov/frpc/files/1067931/run_testdriver.sh.patch.txt)

**Comment by mlngan** [comment]
Thank you for your feedback.  This issue has been addressed in https://github.com/usnistgov/frpc/commit/aabdbea0f929ebe963639ed3a9e35b08e416ad7b.
